// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pinya_Presentations.Db;

#nullable disable

namespace Pinya_Presentations.Migrations
{
    [DbContext(typeof(Database))]
    [Migration("20250802135826_ver2")]
    partial class ver2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pinya_Presentations.Db.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("Pinya_Presentations.Db.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Pinya_Presentations.Db.EmployeeFamilyMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeFamilyMembers");
                });

            modelBuilder.Entity("Pinya_Presentations.Db.Candidate", b =>
                {
                    b.OwnsOne("Pinya_Presentations.Db.PersonalName", "Name", b1 =>
                        {
                            b1.Property<int>("CandidateId")
                                .HasColumnType("int");

                            b1.Property<string>("Degrees")
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)");

                            b1.Property<string>("DegreesBehind")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Firstname")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Lastname")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Middlename")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("CandidateId");

                            b1.ToTable("Candidates");

                            b1.WithOwner()
                                .HasForeignKey("CandidateId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Pinya_Presentations.Db.Employee", b =>
                {
                    b.OwnsOne("Pinya_Presentations.Db.PersonalName", "Name", b1 =>
                        {
                            b1.Property<int>("EmployeeId")
                                .HasColumnType("int");

                            b1.Property<string>("Degrees")
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)");

                            b1.Property<string>("DegreesBehind")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Firstname")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Lastname")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Middlename")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("EmployeeId");

                            b1.ToTable("Employees");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Pinya_Presentations.Db.EmployeeFamilyMember", b =>
                {
                    b.HasOne("Pinya_Presentations.Db.Employee", "Employee")
                        .WithMany("EmployeeFamilyMembers")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Pinya_Presentations.Db.PersonalName", "Name", b1 =>
                        {
                            b1.Property<int>("EmployeeFamilyMemberId")
                                .HasColumnType("int");

                            b1.Property<string>("Degrees")
                                .HasMaxLength(64)
                                .HasColumnType("nvarchar(64)");

                            b1.Property<string>("DegreesBehind")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Firstname")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Lastname")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Middlename")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("EmployeeFamilyMemberId");

                            b1.ToTable("EmployeeFamilyMembers");

                            b1.WithOwner()
                                .HasForeignKey("EmployeeFamilyMemberId");
                        });

                    b.Navigation("Employee");

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Pinya_Presentations.Db.Employee", b =>
                {
                    b.Navigation("EmployeeFamilyMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
