<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>791b3c27-a08c-489c-b81f-1cecb80dddd8</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SendGrid" Version="9.29.3" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Kendo.Mvc">
      <HintPath>..\..\..\..\..\..\Resources\DLL\KendoUI_core_23\Kendo.Mvc.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
